### ISSUE TITLE
Proposal: remove include()

### ISSUE THREAD

**Issue by cjihrig** [hapijs/code#100]
I'm proposing removing `include()`. It's too magical. There are too many modifiers, and there are differences for arrays, objects, and strings. I don't think anyone actually knows how this behaves 100% of the time.

If no one strongly objects, I'd like to remove this in the next major release.

**Comment by vdeturckheim** [comment]
:+1: on that

**Comment by hueniverse** [comment]
I need everything it does, but if you want to break it into individual use cases, that's ok.

**Comment by AdriVanHoudt** [comment]
@Marsup you reacted with a "sad face" does that mean you also use it and don't want it removed?

**Comment by Marsup** [comment]
Yes. I adhere to what @hueniverse said, can't quantify how much of those features I use though. Although most of my use cases could probably be covered by something akin to [`jasmine.objectContaining`](https://jasmine.github.io/2.1/introduction.html#section-Partial_Matching_with_%3Ccode%3Ejasmine.objectContaining%3C/code%3E). Reminds me a bit of joi so maybe a better api can be found...

**Comment by cjihrig** [comment]
I'm just going to leave this as is.

**Comment by hueniverse** [comment]
@cjihrig I agree it does a bit of magic right now. It would be cool to be more expressive like `expect(x).to.be.an.array.containing()` or `expect(x).to.be.an.object.withKeys()`.

**Comment by cjihrig** [comment]
Since `include()` is basically [just a call to `Hoek.contain()`](https://github.com/hapijs/code/blob/461fdb1c0cffd5227b4a18ac1698ad75aaa22017/lib/index.js#L206-L213), it might be more work and breakage than it's worth. It's not like we'd be reducing complexity, so I'd rather not break existing tests.
