### ISSUE TITLE
Allow custom validation function for reject 

### ISSUE THREAD

**Issue by kanongil** [hapijs/code#106]
The new `await reject` that helps test promise rejections only supports two specific validation methods on the returned error.

It would be much more useful, if it can support additional custom validation, either through a callback, or by returning the error.

Example:

```js
await expect(somePromise).to.reject((err) => {

    expect(err.isBoom).to.exist();
});
```

Alternatively:

```js
const err = await expect(somePromise).to.reject();
expect(err.isBoom).to.exist();
```

This mode looks cleaner, but is a bit weird, since it requires `reject` to resolve with the error.

**Comment by hueniverse** [comment]
I had the same thought as I was rewriting the tests and had to use try...catch instead of an assertion where the test needed extra checks. I'll add this today. I think we can support both options...
