### ISSUE TITLE
5.1.0 fails to load

### ISSUE THREAD

**Issue by jtlapp** [hapijs/code#108]
Running the following:

```javascript
const Code = require('code');
```

Produces the following error:
```
/Users/joe/repos/myserver/node_modules/code/lib/index.js:402
internals.reject = async function (/* type, message */) {
                         ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/joe/repos/myserver/test/t_check.js:1:76)
    at Module._compile (module.js:570:32)
```

Code works as expected when I back out to `code@4.1.0`.

Running node v.6.9.1 on a Mac.

**Comment by cjihrig** [comment]
Version 5 includes the use of `async` functions, which are not present in Node 6. The new version only supports Node 8.

**Comment by jtlapp** [comment]
Okay thanks. You could have saved both of us time by making this clear on the readme page.

**Comment by hueniverse** [comment]
@jtlapp this is all on you. You either started using this today and never bothered to look at the package information, or you have been using this for a while and just upgraded without bothering to find out why this is a major version change. Clearly this includes a breaking change. Who upgrades without knowing what is actually included?!

The only person wasting people's time is you.

**Comment by jtlapp** [comment]
I'm reading a book on hapi.js and followed the instructions to install `code`.

**Comment by jtlapp** [comment]
I did read the 5.x version history for notes, but there weren't any. It's just a matter of how helpful you want to be to people who are trying to get up to speed.

I apologize for the frustration in my original response. It did cost me a bit of time, but that's only an explanation, not an excuse.

**Comment by hueniverse** [comment]
@jtlapp Attitude matters. I have a zero tolerance policy when it comes to people expressing even slight hints of entitlement. I appreciate your response and clarification.

As for the issue, you showed up right in the middle of a major transition to node v8 and full async/await interface. This is going to break a lot of stuff. You should pay attention to versions if you don't want to run node v8. This will be sorted out in a couple of weeks.
