### ISSUE TITLE
Testing the construction of a class

### ISSUE THREAD

**Issue by lvegerano** [hapijs/code#109]
I'm implementing a strategy pattern. I have my context class throw an error when an invalid strategy is passed. I'm not sure how to test this. My context constructors is what throws.

```javascript
constructor(type) {
    this.strategy = null;

    switch (type) {
      case 'reaction':
        /**
         * @type {ReactionStrategy}
         */
        this.strategy = new ReactionStrategy();
        break;
      default:
        throw new Error('Unknown dispatcher strategy');
    }
  }
```

Now on my test I'm trying 
```javascript
expect(new NotificationsDispatcher()).to.throw(Error, 'Unknown dispatcher strategy');
```

Is this possible? Am I doing something wrong?

**Comment by Marsup** [comment]
Put it in a function, `expect(() => new NotificationsDispatcher())`.
