### ISSUE TITLE
Object [object Object] has no method 'startWith'

### ISSUE THREAD

**Issue by dalemanthei** [hapijs/code#11]
We're getting an error attempting to use the startsWith validation. The code in github has the method but the version of code@1.2.1 installed on our system via npm install does not.

I've uninstalled code, cleaned the npm cache, reinstalled. I'm getting a 1.2.1 version of code but it still comes up with the missing function.

Is this an npm related issue or did the code package miss bumping a version number along the way?

**Comment by gergoerdosi** [comment]
1.2.1 has been released before `startWith` was added. Currently it is available only on master.

**Comment by dalemanthei** [comment]
I'm not aware of a way to install from master other than git cloning the project. If there is a way to do that using package.json, that would be cool.  If not, is there an outlook for when 1.2.2 would be bumped and released?

**Comment by gergoerdosi** [comment]
You can specify the GitHub repository in `package.json`:

```
"code": "hapijs/code"
```

**Comment by hueniverse** [comment]
Isn't @cjihrig maintaining this now?

**Comment by cjihrig** [comment]
I am starting now :-)

**Comment by lloydbenson** [comment]
thx @cjihrig!

**Comment by cjihrig** [comment]
This is ready to go, I just need npm publish rights.

**Comment by cjihrig** [comment]
1.3.0 is published
