### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by geek** [hapijs/code#110]
`lib/index.js:263`

When `expect(null).to.have.length(2);`

**Comment by AdriVanHoudt** [comment]
Easy link https://github.com/hapijs/code/blob/a878e86667c05b3974b4456386e2277bb770f02e/lib/index.js#L263

**Comment by AdriVanHoudt** [comment]
would  `this._ref && (this._ref.length !== undefined ? this._ref.length : Object.keys(this._ref).length)` fix it?

**Comment by cjihrig** [comment]
@AdriVanHoudt want to submit a PR and find out 😄 ?
