### ISSUE TITLE
node lts

### ISSUE THREAD

**Issue by philkunz** [hapijs/code#112]
Shouldn't node lts (6.x.x) be supported?

Currently you restrict node to 8.x.x ...

**Comment by AdriVanHoudt** [comment]
If you want a version that supports node < 8.x.x use v4.x.x of this module

**Comment by philkunz** [comment]
fair enough. Any particular reason for not supporting node 6 lts?

**Comment by hueniverse** [comment]
The entire hapi ecosystem is moving to node 8.
