### ISSUE TITLE
Standalone?

### ISSUE THREAD

**Issue by machineghost** [hapijs/code#113]
I'd like to use the HapiJS Code library without the rest of the HapiJS framework: is that possible, and if so what `npm` package should I use?

**Comment by Marsup** [comment]
code?

**Comment by machineghost** [comment]
As in this library/package, https://github.com/hapijs/code

**Comment by hueniverse** [comment]
Our efforts are aimed at people using the hapi.js framework. Helping people use components for other use cases is fine, but not a priority or worth our limited resources.

**Comment by machineghost** [comment]
Fair enough.  I mean, I don't think adding a single `npm i` line to a readme is a huge use of resources, but I totally get your point that even 0.000001 units of effort for something irrelevant is too much.

**Comment by hueniverse** [comment]
It's kinda silly request though. If you cannot read a package.json file yourself and figure out how to install a package. that level of documentation is just useless.

**Comment by machineghost** [comment]
I'd respond about how much packages (let alone most sub-packages of a larger framework) don't have a name of `code`, but at this point you could have added the line in the time it took you to respond to me, so if your goal is not to waste time I won't continue wasting your time by trying to convince you.
