### ISSUE TITLE
 reject does not fail if argument is of the wrong type

### ISSUE THREAD

**Issue by ferrao** [hapijs/code#119]
I expected the following test to fail:
```javascript
it('should fail', async () => {
        const promise = Promise.reject(new Error('some error message'));
        await expect(promise).to.reject(Error, {});
        await expect(promise).to.reject(Error, []);
        await expect(promise).to.reject(Error, null);
        await expect(promise).to.reject(Error, undefined);
        await expect(promise).to.reject(Error, NaN);

});
```
But surprisingly it does not. From the documentation, it is clear that the second argument to `reject()` needs to be a string or a regex, but would it not be safer to make the test fail if that is not the case?

**Comment by cjihrig** [comment]
Thanks for reporting this. I don't have the time to address this right now, but I'll take a PR to fix it.

**Comment by ferrao** [comment]
I have submitted a PR submitted @cjihrig , can you review it please?
