### ISSUE TITLE
Assertions on error properties

### ISSUE THREAD

**Issue by dominykas** [hapijs/code#123]
Ran into a use case recently, where I'd like to assert on error codes and some more meta information. 

I'm thinking about `error([type], [message], [values])` / `throw([type], [message], [values])`, e.g.

```
expect(() => someMethod()).to.throw(CustomError, 'Oh no!', { code: 'E_NOENT' });
```

This would essentially do an extra `expect(error).to.include(values);` - there is no other way to check this when using `to.throw()` AFAIK?

Happy to PR if acceptable.

**Comment by mtharrison** [comment]
Sounds useful to me. Not sure if I'd be expecting `includes()` as you suggest or a deep equality check though.

**Comment by dominykas** [comment]
Yeah, I was thinking about deep vs includes. But with error objects it may be hard to always assert the deep copy - there may be functions on it or other things you don't control, so a loose check feels more useful in practice. I couldn't come up with a nice way to make it optional - adding a fourth param would be pretty ugly? I also considered making the third param a function which receives the error thrown - but that feels overkill?

Another option would be to have something like `error([type], [values], [options])`, e.g.

```
expect(() => someMethod()).to.throw(CustomError, { message: 'Oh no!', code: 'E_NOENT' }, { strict: true });
```

Possibly leave out the `{ strict: true }` as a future extension (if someone asks for it) and until then the second param is either a `message` or a `values` object for an `includes()` check?

**Comment by cjihrig** [comment]
I'll entertain a PR for this 😄

**Comment by dominykas** [comment]
@cjihrig any opinion on the API, before I jump into this? :)

**Comment by hueniverse** [comment]
I'll replicate our `reject()` interface style and just return the error for further, separate assertions.

**Comment by mtharrison** [comment]
So one would do the following?

```js
const err = expect(() => someMethod()).to.throw(CustomError);
expect(err).to.include({ code: 'E_NOENT' });
```

**Comment by hueniverse** [comment]
Yes.
