### ISSUE TITLE
new Type -> class

### ISSUE THREAD

**Issue by woolfi182** [hapijs/code#127]
I think you need to add a new type 'class' for testing whether it is a class or not. Right now you need to use 'function' instead or try to create an instance of a class.

**Comment by cjihrig** [comment]
What would the check look like to differentiate a class from a function (without stringifying the function), and why do you need it (since it's just a function)?

**Comment by woolfi182** [comment]
So, Let's imagine the situation when you don't want to create an instance of a class but you want to know that it is a class.
```javascript
expect(SomeClass).to.be.a.class()
```
Now, for checking whether it is a class I'm doing something like this:
```javascript
expect(SomeClass).to.be.an.object();
expect(SomeClass.prototype).to.be.an.object();
expect(SomeClass.prototype.constructor).to.be.a.function();
```
or
```javascript
const s = require('selectn');

expect(SomeClass).to.be.an.object();
const constructor = s('prototype.constructor',SomeClass);
expect(constructor).to.be.a.function();
```

**Comment by devinivy** [comment]
I don't need this in code, but I have run into a case where this kind of check was necessary.  Imagine your library handles input that can either be a value or a function that lazily returns a value.  If that value is allowed to be anything (including a class), then you'd want this check.  After some research, this how I ended-up implementing it,
https://github.com/devinivy/haute/blob/6ad38373c5a610d1f65c93056ec01ba59b000873/lib/index.js#L142

**Comment by AdriVanHoudt** [comment]
Seems to be the conventional way to test it https://github.com/miguelmota/is-class/blob/master/is-class.js#L10

**Comment by cjihrig** [comment]
I'm **really** not a fan of relying on the `toString()` behavior of functions. It seems flimsy and prone to change (not to mention it looks like Babel requires special casing). We've already got enough of this type of thing going on with stack trace parsing.

**Comment by cjihrig** [comment]
Follow up question: do any popular assertion libraries support this?

**Comment by hueniverse** [comment]
I don't see the point.

**Comment by woolfi182** [comment]
@cjihrig Not exactly
Using Jest you are able to do things like shown here https://jestjs.io/docs/en/es6-class-mocks#manual-mock
But it doesn't have a specific data type 'class'
