### ISSUE TITLE
Remove engines

### ISSUE THREAD

**Issue by hueniverse** [hapijs/code#130]

**Comment by athaax** [comment]
Why remove 'engines' if the package isn't compatible with older versions of node? Tried pulling in this library on a node 6.11.0 project but it uses async/await, which isn't supported in that version. This would have at least provided that warning.

**Comment by cjihrig** [comment]
It was removed because the `engines` field doesn't help much. It only prints an easy to miss warning during `npm install`.

**Comment by hueniverse** [comment]
Removed mostly due to inconsistent handling between npm and yarn.
