### ISSUE TITLE
Expect Array of Objects to Include Object is requiring an exact match

### ISSUE THREAD

**Issue by zaclittleberry** [hapijs/code#137]
I'm not sure if this is a bug or a feature request because the examples in the api docs do work, but they are simple, and assumptions based on how the separate pieces work, when combined together do not work in this case. Thank you for the awesome library by the way. not complaining, just want to figure out if this is a bug or if I should do things differently! :)

I am trying to check if an array of objects that includes an object (with only matching some of the keys in the object).

```
expect({a:2, b:2}).to.include({a:2}); // works
expect([{a:1, b:1}, {a:2, b:2}]).to.include({a:2}); // fails
expect([{a:1, b:1}, {a:2, b:2}]).to.include([{a:2}]); // fails
expect([{a:1, b:1}, {a:2, b:2}]).to.include({a:2, b:2}); // works
expect([{a:1, b:1}, {a:2, b:2}]).to.include([{a:2, b:2}]); //works
```

The first `expect` demonstrates the 'sub object' type include I'm trying to do.

The second `expect` was my attempt to try an include of a sub object within an array.

The third `expect` was in case include's value had to be an array.

The fourth `expect` shows that an exact object match works with expect array.

The fifth `expect` shows that an exact object in an array works with expect array.

**Comment by hueniverse** [comment]
This works as expected. The partial comparison only works on one level. If it is an array, it needs to find exact match of some items. If it is an object, exact match of some keys. An array of object doesn't get both...
