### ISSUE TITLE
do not truncate values in assertions

### ISSUE THREAD

**Issue by csrl** [hapijs/code#14]
I have a simple lab test that asserts:
```javascript
expect(err).to.not.exist();
```
And when it asserts I get output that looks something like:
```
Expected { Object (code, status, ...) } to not exist
```
Which doesn't provide the context I need to understand the failure.  So I have to go back into the test case, add a debug line like
```javascript
console.log(err);
```
and then rerun the tests to actually see what is going wrong.  It'd be nice if the value was not being truncated/formatted like that.

**Comment by cjihrig** [comment]
I'll take a PR for this.
