### ISSUE TITLE
to.only.include(values) passes with values not in reference

### ISSUE THREAD

**Issue by samliebow** [hapijs/code#146]
https://github.com/hapijs/code/issues/143 wasn't the whole story: `to.only.include` still has incorrect behavior after the fix that solved that. The underlying issue is [on Hoek](https://github.com/hapijs/hoek/issues/327), but filing here for reference.

This passes on 5.2.1 and fails at higher versions:
```
describe('to.only.include', function() {
    it('should not pass with values not in the reference', function() {
        function shouldThrow() {
            expect(['a', 'b']).to.only.include(['a', 'b', 'c'])
        }
        
        expect(shouldThrow).to.throw()
    })
})
```

**Comment by hueniverse** [comment]
No need to keep opening duplicate issues.
