### ISSUE TITLE
.to.deep.equal() performs unexpectedly with empty object

### ISSUE THREAD

**Issue by bruderstein** [hapijs/code#15]
Due to [Hoek's deepEqual funtion](https://github.com/hapijs/hoek/blob/master/lib/index.js#L250)  only checking existing properties in the "left" object, thereby allowing the right object to be a superset of the left, means that an empty object always passes.

e.g.
If you have the following
```javascript
var result = testInstance.getCurrentUser();
expect(result).to.deep.equal({ user: 'steve', id: 14 });
```

If getCurrentUser() returns an empty object, this will pass, which is probably unexpected.
You get a "better" result, by doing the (unintuitive) reverse:

```javascript
expect({ user: 'steve', id: 14 }).to.deep.equal(result);
```

This fails if the user or id properties are not equal, but passes if result has extra properties. 

The initial "quick fix" could be to just swap the arguments to Hoek.deepEqual, which would be "better" behaviour, although that still needs to be made clear in the docs.

**Comment by cjihrig** [comment]
Thanks for reporting this. This sounds more like an issue with Hoek. Can you open an issue over there? Once fixed, Code can be updated with the fix.

**Comment by hueniverse** [comment]
Better to keep this open until it is resolved in hoek and verified here.
