### ISSUE TITLE
Assertion with 'equal()' fails

### ISSUE THREAD

**Issue by emarkk** [hapijs/code#152]
#### Support plan

* *which support plan is this issue covered by?*: community
* *is this issue currently blocking your project?*: yes
* *is this issue affecting a production system?*: no

#### Context

* *node version*: 12.11.0
* *module version*: 7.0.0
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi backend
* *any other relevant information*: using with mongodb, mongoose

#### How can we help?

I'm doing basic tests, and I have problems with the following simple assertion
```
expect(all.classes).to.equal(testData.classes);
```

![image](https://user-images.githubusercontent.com/20368644/69100579-c0235a00-0a5d-11ea-9816-a04ef0a67784.png)

Is this a deepEqual problem? When I do
```
expect(JSON.stringify(all.classes)).to.equal(JSON.stringify(testData.classes));
```
everything works fine, indeed they are equal.

**Comment by hueniverse** [comment]
Look for keys with undefined values.
