### ISSUE TITLE
Expect object to have property

### ISSUE THREAD

**Issue by Marsup** [hapijs/code#16]
Hi,

Coming from chai, I'm quite used to do things like `expect(obj).to.have.property('a').that.equals('foo')`.
What do you think of adding that to code ?

**Comment by AdriVanHoudt** [comment]
Can you do `expect(obj.a).to.exist().and.to.equal('foo')`?

**Comment by Marsup** [comment]
Less elegant but yes that would work. I'll wait for @cjihrig to advise on whether we add this.

**Comment by cjihrig** [comment]
I personally prefer @AdriVanHoudt's version, but I would take a PR for this.

**Comment by hueniverse** [comment]
I purposely didn't include it because `expect(obj).to.contain({ a: 'foo' })` does the trick just fine.

**Comment by AdriVanHoudt** [comment]
I prefer Eran's solution but it doesn't allow you to do `expect(obj.a).to.exist().and.to.contains('foo')`

**Comment by hueniverse** [comment]
What's the diff? if `obj.a` doesn't exist, my assertion will fail.

**Comment by AdriVanHoudt** [comment]
In your case you check if `obj` has the property `a` with value `foo` in my case you check if  `obj.a` contains the value `foo` so it can also be `foo bar` or am I doing it wrong?

**Comment by hueniverse** [comment]
Ah, you are using the string version. I generally avoid using partial comparisons...

**Comment by AdriVanHoudt** [comment]
Ah yes if you take the original request your version would be better

**Comment by Marsup** [comment]
Does it work for deep equal as well ? Like `expect(obj).to.contain({ a: { foo: 'bar' }})`.
Is it partial ? (ie. a may not only contain foo).
I'm trying to also find alternatives to `expect(obj).to.have.deep.property('a.foo').that.equal('bar')`.

**Comment by hueniverse** [comment]
It should. Look at the tests in both hoek and code.

**Comment by Marsup** [comment]
Well nope :
```js
> Code.expect({ foo: { bar: 'baz', foo: 'bar' }}).to.deep.include({ foo: { bar: 'baz' } })
Error: Expected { foo: { bar: 'baz', foo: 'bar' } } to include { foo: { bar: 'baz' } }
```
