### ISSUE TITLE
The type `.rejects` returns  should return a Promise

### ISSUE THREAD

**Issue by gerardolima** [hapijs/code#160]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: v14.15.4
* *module version with issue*: "@hapi/code": "^8.0.2"
* *last module version without issue*: unknown
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): "@hapi/lab": "^24.1.1"
* *any other relevant information*: Code is developed in TypeScript.

#### What are you trying to achieve or the steps to reproduce?

```ts
const myFunc = async () => { throw new Error('not implemented') }
it('rejects with "not implemented"', async () => {
  // WARNING: the following `await` is correct and intentional
  await expect(myFunc()).rejects(/not implemented/)
})
```

#### What was the result you got?
TypeScript compiler shows the warning `'await' has no effect on the type of this expression.ts(80007)` and eslint triggers the following error:

```shell
$ eslint './src/**/*.ts' 

xx/index.spec.ts
  xx:3  error  Unexpected `await` of a non-Promise (non-"Thenable") value  @typescript-eslint/await-thenable

1 problem (1 error, 0 warnings)
```
#### What result did you expect?
No compiler warning neither linter error.

**Comment by kanongil** [comment]
Created #161 which should fix this issue.
