### ISSUE TITLE
Rename module

### ISSUE THREAD

**Issue by toymachiner62** [hapijs/code#22]
Trying to do a google search for "hapi code", "npm code" or anything else is brutal for finding this module. Everything related to hapi itself, or node itself comes up.

I feel the name was not thought out very well and i suggest it be renamed b/c it's almost impossible to find this module on github, npm, or google.

**Comment by cjihrig** [comment]
I understand where you're coming from. Unfortunately, we're not going to rename it.

**Comment by hueniverse** [comment]
Maybe it was a secret and you just ruined it.

**Comment by toymachiner62** [comment]
Doh :exclamation:

**Comment by dougwilson** [comment]
Another option is to simply use DuckDuckGo for searches: https://duckduckgo.com/?q=npm+code&ia=software

**Comment by AdriVanHoudt** [comment]
@dougwilson I can't find it with duckduck either :p
