### ISSUE TITLE
`settings.truncateMessages = false` causes issues with deep object comparisons

### ISSUE THREAD

**Issue by marshall007** [hapijs/code#30]
It looks like the line on [`lib/index.js#L344`](https://github.com/hapijs/code/blob/92ebc19d88bec95f894b72efec6a24f12184e46c/lib/index.js#L344) assumes that the message portion of `error.stack` will only be one line (i.e. the `.slice(1)`). However, when `Code.settings.truncateMessages = false` the object is pretty-printed and the stacktrace looks like this:

```
Error: Expected { foo: 'bar'
  hello: 'world' } to equal specified value
  at ...
```

**Comment by cjihrig** [comment]
Published in v1.4.1
