### ISSUE TITLE
once flag should change error message

### ISSUE THREAD

**Issue by mtharrison** [hapijs/code#47]
The `once` flag doesn't change the error message:

 `expect([1,2,2]).to.once.include(2);` => `Error: Expected [ 1, 2, 2 ] to include 2`

Which looks kinda weird because it does include 2. I think `once` should change the error message as `not` does:

`expect([1,2,2]).to.not.include(2);` => `Error: Expected [ 1, 2, 2 ] to not include 2`

**Comment by cjihrig** [comment]
I'll take a PR for this if anyone feels like working on this before I get to it.
