### ISSUE TITLE
Add mention on README to go for 1.5.0 for node 0.10

### ISSUE THREAD

**Issue by AdrieanKhisbe** [hapijs/code#49]
cf https://github.com/hapijs/lab/issues/502

(If there is an agreement, I can take care of the Fork&PR)

**Comment by Marsup** [comment]
Probably same answer as in lab then.

**Comment by AdrieanKhisbe** [comment]
for sure :)

**Comment by cjihrig** [comment]
My issue with this is that you would have to maintain a list indefinitely of when support was dropped for every version of Node.

**Comment by AdrieanKhisbe** [comment]
Not necessary. the information is of no use when the node version maintenance ends.

cf https://medium.com/@nodesource/essential-steps-long-term-support-for-node-js-8ecf7514dbd#.6kvx32z6l

Beside this would at most occurs one per breaking changes.

**Comment by cjihrig** [comment]
> Not necessary. the information is of no use when the node version maintenance ends.

You would think so. People still use Node 0.8 despite it being unsupported for a while now. The same thing will happen with 0.10 and every version after it.

I'm open to whatever is decided on across the majority of the hapijs org. My personal opinion is to not include it though.

**Comment by AdrieanKhisbe** [comment]
cf https://github.com/hapijs/lab/issues/502#issuecomment-166671419
