### ISSUE TITLE
Question: how to attach message to expectation

### ISSUE THREAD

**Issue by AdrieanKhisbe** [hapijs/code#50]
I'm currently porting some test from `mocha` to `lab`and `code`, 
and I need to convey some expectation message that carry important knowloedge,
the intent of the expectation.

*Is it possible to currently attach a custom message in case an expection fail?*
I look in the api and it doesn't seems so. But I might have miss it

Otherwise would you be open in some PR adding this feature?

**Comment by gergoerdosi** [comment]
You can add a prefix with the current code:

https://github.com/hapijs/code/blob/master/test/index.js#L125

**Comment by AdrieanKhisbe** [comment]
@gergoerdosi I saw :)
However, not sure it's the point of the prefix argument.

**Comment by cjihrig** [comment]
Prefix does what you're looking for. There isn't a way to completely remove the default assertion though.

**Comment by AdrieanKhisbe** [comment]
thanks @cjihrig. wil be then using that :)

**Comment by AdrieanKhisbe** [comment]
(add `question` label too, so that eventual user with same question might more likely end up there :) )

**Comment by cjihrig** [comment]
Done :-)

**Comment by AdrieanKhisbe** [comment]
:+1:
