### ISSUE TITLE
Proposal of expect.call helper syntax

### ISSUE THREAD

**Issue by AdrieanKhisbe** [hapijs/code#52]
Checking if a function call trigger an exception required currently to use a function expression to wrap the function call.
Though this is simplified with arrow function, it's still not that readable.

An alternative would be to add a `expect.call(<myfunction>).with(<args>)` syntax.

I can take care of the implementation if this proposal meets positive reactions.

--------
Here is a real motivation example from Joi to illustrate use case: https://github.com/hapijs/joi/blob/master/test/function.js#L77-L93

      expect.call(Joi.func().minArity).with(0).to.throw(Error, 'n must be a strict positive integer');
       // instead of
       const schemaWithZeroArity = function (){

            return Joi.func().minArity(0);
        };
        expect(schemaWithZeroArity).to.throw(Error, 'n must be a strict positive integer');

**Comment by cjihrig** [comment]
I can see how this would be helpful. Two things though:

1. I would make the syntax `expect(fn).calledWith(this, arg1, arg2).to.throw(...);`
2. Why not just use `Function.prototype.bind()`?

**Comment by AdrieanKhisbe** [comment]
about the implem, `bind` was the idea ;)

**Comment by AdrieanKhisbe** [comment]
and indeed, your syntax is even better!! :D

**Comment by cjihrig** [comment]
I personally think it's more readable to do the bind by hand. That way you only have to understand native JavaScript, instead of `code` specifics. It might actually be less to type anyway.

However, I'm open to hearing what other people think.

**Comment by AdrieanKhisbe** [comment]
One problem of `bind` is the first argument:
cf https://github.com/hapijs/joi/pull/787#discussion_r48454315 (by habits I went for `null`...).

Beside I don't find it more explicit. I feel it *cloud* test intent which is more *calling the function and getting an error*, than binding value.

I would also tend to not put `this` in calledWith. Most of the function not really use `this`

But for sure, allways better to understand native js! :D

**Comment by AdrieanKhisbe** [comment]
I started working on this. Shall I open a *WIP PR* to get feedback, and propose a basis for discusstino?

**Comment by AdrieanKhisbe** [comment]
after first draft and replexion was more thinking about something like:

 `expect(fun).call.with(<args>).on(<this>).to.throw()``

The `with` and `on` being facultative.

A `return(value)` could also be added to check the return eventually. (as I had first wrote test)

**Comment by gergoerdosi** [comment]
Expect.js had `withArgs`:

> **withArgs:** creates anonymous function to call fn with arguments
> ```js
> expect(fn).withArgs(invalid, arg).to.throwException();
> ```

How about dropping `call` and just using `with`? I think it reads quite well:

```js
expect(fn).with(<args>).to.throw();
```

**Comment by cjihrig** [comment]
@hueniverse thoughts?

**Comment by AdrieanKhisbe** [comment]
@gergoerdosi Good suggestion, I followed it, adding some aliases.

cf 2f162c2113aef228d390a3a34ed502ec07e4b3c3

**Comment by AdrieanKhisbe** [comment]
Hapi New Year @all :)

Has a logical sequel of previous changes I introduced a `result` function to call the function and be able to assert on the result.

Was hesitating to add some alias names like `return`. Any suggestion is welcome

**Comment by cjihrig** [comment]
The more I think about this, the less I like it. You have to add APIs for calling the function, getting the return result, setting `this`, etc. Just seems like a lot of unnecessary complexity when JavaScript gives you everything you need to do this just as simply, if not simpler.

I'm going to go ahead and close this.

**Comment by AdrieanKhisbe** [comment]
Sure it's just sugar around javascript features.
But are as most of assert already in code! :)

**The point of this is to enable writing test in a very succint way.**
Without having noise around to define function you don't need.

cf [motivation example:](https://github.com/hapijs/joi/blob/master/test/function.js#L77-L93)

-------
    expect.call(Joi.func().minArity).with(0).to.throw(Error, 'n must be a strict positive integer');

vs

    const schemaWithZeroArity = function (){

        return Joi.func().minArity(0);
    };
    expect(schemaWithZeroArity).to.throw(Error, 'n must be a strict positive integer');

With three test like that it's 3 lines instead of 15!!
Beside the asserter capture semantics.

**Comment by cjihrig** [comment]
Just use `bind()` and it's still 3 lines.

Another reason I don't like this proposal is that you need to be able to set `this`, or else it's incomplete (unless you're dealing with arrow functions, but there is no way to tell that). Just a can of worms that I don't want to open.

> Sure it's just sugar around javascript features.
But are as most of assert already in code! :)

To be honest, I wouldn't have accepted some of the existing features like the type checking functions. It's REALLY hard to do that accurately (and getting harder) without dropping down to the C++ layer.

**Comment by AdrieanKhisbe** [comment]
> To be honest, I wouldn't have accepted some of the existing features like the type checking functions. It's REALLY hard to do that accurately (and getting harder) without dropping down to the C++ layer.

That's because it's hard it's better to rely on a library to do this correctly (haence relying on a developer to fight the C++ layer for us :), thanks for that).
From a library user it's a powerful abstraction.

> you need to be able to set this, or else it's incomplete (unless you're dealing with arrow functions, but there is no way to tell that). Just a can of worms that I don't want to open.

Are you refering to the `on`syntax?
And what king of worms you fear to come out of this?
