### ISSUE TITLE
Problem with internals.at

### ISSUE THREAD

**Issue by simon-p-r** [hapijs/code#57]
Hi

I am having a problem with this line https://github.com/hapijs/code/blob/master/lib/index.js#L435, due to the value of "const at". Sometimes the value is null meaning the return value from function throws an error and then shows "thrown errors in test" message in tests being run by lab.

**Comment by cjihrig** [comment]
Can you provide an example?

**Comment by simon-p-r** [comment]
Not easily, it was due to a thrown ENONENT error.  I resolved by destroying a path and recreating for every test run by lab.

**Comment by cjihrig** [comment]
Reproduction:

```javascript
const Fs = require('fs');
const Code = require('code');

Fs.readFile('./thisfiledoesntexist', (err) => {
  Code.expect(err).to.not.exist();
});
```

I'll try to get to this over the weekend.
