### ISSUE TITLE
shows “actual” “expected” (red, green) but doesn't show a red or green point of failure.

### ISSUE THREAD

**Issue by fourq** [hapijs/code#59]
seems to have a bug where a test fails and shows “actual” “expected” (red, green) but doesn't show a red or green point of failure

I see this mainly on large JSON `expect(…).to.deep.equal(…);`

```js
server.inject(options, (res) => {
    expect(res.result).to.deep.equal(fakeMappedForms);
    done();
});
```

`res.result` an `fakeMappedForms` can be found [here](https://gist.github.com/fourq/68dded1e9218f1dd83b3)

**Comment by gergoerdosi** [comment]
This sounds like a [lab](https://github.com/hapijs/lab) issue. Code doesn't have coloring.

**Comment by fourq** [comment]
I'll create over there and link to here as well, thanks

**Comment by cjihrig** [comment]
If the only issue is coloring, then it's a lab issue.

**Comment by cjihrig** [comment]
So I'm not sure how you expect me to test this. You provided a single object. I created a script and assigned separate copies of the large object to two different variables and compared via `Code.expect(foo).to.deep.equal(bar);`. The comparison passed. I tried modifying a single field in one of the objects, and the comparison caught the change. I'm going to close this for now. If you can provide an executable reproduction, I'd be glad to take a look at it.

**Comment by fourq** [comment]
interesting. around noon today I'll add a reasonable issue response

**Comment by cjihrig** [comment]
One more thing. Under the hood, `code` just calls [`Hoek.deepEqual()`](https://github.com/hapijs/hoek#deepequalb-a-options). If you are able to verify that the comparison isn't working, please try `Hoek.deepEqual()` as well.
