### ISSUE TITLE
is there a "definitelytyped" definition for code

### ISSUE THREAD

**Issue by sulhome** [hapijs/code#60]
I wonder if there is a "definitelytyped" definition for code. This is very helpful in IDE's like WebStorm as it is reporting a lot of weak warnings for things like `to.be.true()`. These warnings will disappear if you download the "definitelytyped" definition

**Comment by cjihrig** [comment]
I have no clue. If you mean an entry in https://github.com/DefinitelyTyped/DefinitelyTyped, then it doesn't look like it.
