### ISSUE TITLE
mocking methods & properties

### ISSUE THREAD

**Issue by atlanteh** [hapijs/code#66]
Is there any way or a plan to add mocking for methods, checking how many times a method was called, etc.?
In a server env, I want to test every component on its own, and its impossible without mocking methods.

**Comment by hueniverse** [comment]
That's probably out of scope. Why not use sinon or other such solutions?

**Comment by cjihrig** [comment]
Yea, I don't think that really belongs in an assertion library. You could just monkey patch the methods by hand, or use something like `stand-in`.
