### ISSUE TITLE
ability to match on non-specific array item

### ISSUE THREAD

**Issue by danielb2** [hapijs/code#67]
On non-ordered arrays (arrays not always coming back in specific order), it would be nice to be able to do a match on an item you know to be in there somewhere.

Example:

``` javascript
expect(res.headers['set-cookie']).to.include.match(/session/);
```

**Comment by arb** [comment]
Wouldn't that be the same as 

``` javascript
expect(res.headers['set-cookie']).to.match(/session/);
```

**Comment by cjihrig** [comment]
Hm, the documentation should be updated to make it clear that `match()` handles more than just strings. It looks like the `expect()`ed thing is `toString()`ed before testing against the regex.

**Comment by cjihrig** [comment]
And a test or two would be nice :-)

**Comment by danielb2** [comment]
Hm, the below fails

```
expect(['hello', 'hi']).to.match(/^hi/);

// =>   Expected [ 'hello', 'hi' ] to match /^hi/
```

**Comment by danielb2** [comment]
It looks to me that what it does is a toString() on the array. But that's not the same as individually matching each item in the array

**Comment by cjihrig** [comment]
Yea. The array `toString()` adds the `[ ` to the start of the string that is tested. So we would need a separate API to work on array elements.

**Comment by cjihrig** [comment]
I think what we would want here is `deep.match()`. The other `deep` stuff relies on `Hoek` though. I don't think there is support there for this.

**Comment by blacksun1** [comment]
Would I be right in thinking that these would be valid expectations?

```js
Code.expect(['hello', 'hi']).to.match(/^hi/);
Code.expect(['hello', 'hi']).to.match(/^hi$/);
Code.expect(['hello', 'hi']).to.match(/^hello$/);
Code.expect(['hello', 'hi']).to.not.match(/^Hello$/);
Code.expect(['hello', 'hi']).to.match(/^Hello$/i);
Code.expect(['hello', 'hi']).to.match(/ell/);
Code.expect(['hello', 'hi']).to.match(/h/);
Code.expect(['hello', 'hi']).to.not.match(new RegEx(['hello', 'hi'].toString()));
```

Anything missing from this list that you can think of?

**Comment by cjihrig** [comment]
Yes, I suppose those assertions seem valid. Although, to be honest, I find this API to be a little too magic. Same with the `include()` API.

**Comment by blacksun1** [comment]
Would it be better just to make certain that match, by default, only works on strings and fails on anything else. 

If it was popular enough someone could propose to have another assertion for array matching. It feels like it should be something like includeMatch or something.

**Comment by cjihrig** [comment]
> Would it be better just to make certain that match, by default, only works on strings and fails on anything else.

If I was starting from scratch, I'd say yes. At this point, maybe we should go with a documentation update to `match()` saying that the reference value is converted to a string before testing the regex.
