### ISSUE TITLE
Enforce semantic commit messages

### ISSUE THREAD

**Issue by rodoabad** [hapijs/code#74]
`code` is now `3.0.0`, however there wasn't any changelog explaining the breaking changes. Us consumers of `code` would like to have a way to know what changes happened.

With semantic commit messages, we can auto-generate changelogs based on commit messages. This also enforces contributors to write better commit messages.

**Comment by hueniverse** [comment]
We use the `breaking changes` label to document these things.

**Comment by cjihrig** [comment]
Also see the 3.0.0 milestone - https://github.com/hapijs/code/issues?q=milestone%3A3.0.0.
