### ISSUE TITLE
`expect(object).to.include/contain` does not work

### ISSUE THREAD

**Issue by Chatatata** [hapijs/code#78]
I have an object (actually, standard mongoose object) like so:

    { _id: 5770d65ff0574d31c139ed4e,
    username: 'test',
    email: 'test@mail.com',
    active: true }

and I want to check fields of it with include/contain:

    Code.expect(result).to.contain('username');

fails. Am I missing something here?

Failure log:

    Expected { _id: 5770da42cc7a52d2c1e83272,
    username: 'test',
    email: 'test@mail.com',
    active: true } to include 'username'

**Comment by Marsup** [comment]
Might be useful to include the actual failure.

**Comment by Chatatata** [comment]
@Marsup added log, thank you.

**Comment by Marsup** [comment]
No stack trace at all ?

**Comment by Marsup** [comment]
What does Object.keys return on your object ?

**Comment by Chatatata** [comment]
I figured out `Object.keys()` returning different keys then I thought. Seems it's a Mongoose object.

Lesson learned: Hapi's `server.inject` method does not actually use regular request pipeline. Objects you replied in injected endpoints directly pass to the response handler after injection. I was expecting it is being converted to string and converted back to JSON again, imitating a HTTP request/response.

**Comment by Marsup** [comment]
That depends on what you take from the response object.
