### ISSUE TITLE
Include does not work for defined properties?

### ISSUE THREAD

**Issue by blacksun1** [hapijs/code#90]
Hey,

I has expected that the following would work - and it doesn't.

```js
  it("include assertion should not fail on definedProperties", (done) => {

    const test = {};
    Object.defineProperty(test, "cake", {
      value: "Chocolate"
    });

    // This passes
    expect(test.cake).to.equal("Chocolate");
    // This does not - shouldn't it?
    expect(test).to.include({"cake": "Chocolate"});

    return done();
  })
```

Is this a bug or a "feature"?

Regards,

**Comment by blacksun1** [comment]
As include is essentially a wrapper for `Hoek.contain` I've opened an issue other with them:

https://github.com/hapijs/hoek/issues/196: contain doesn't support non-enumerable properties defined with defineProperties

**Comment by cjihrig** [comment]
I'm going to let `code` defer to `hoek` here. I looked into it extremely briefly, and it might be as simple as changing from `Object.keys()` to `Object.getOwnPropertyNames()`.

**Comment by cjihrig** [comment]
@blacksun1 thanks for your continued investigation into `code` by the way :-)

**Comment by blacksun1** [comment]
Umm, no worries. It is totally selfish actually - we are slowly moving everything from Mocha/Chai to Code/Lab and any fixes makes my job easier.
