### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by blacksun1** [hapijs/code#91]
Hi, There has been a bunch of new changes made to code over the last few weeks at least. Can these please be released to NPM soon? There hasn't been a release since July.

Thanks in advance,

**Comment by cjihrig** [comment]
I was trying to avoid bumping the major too soon after the 3.0.0 release, which was on May 20th. Looking at the [4.0.0 milestone](https://github.com/hapijs/code/milestone/15?closed=1), #84 and #77 are the only changes to `lib/` code - amounting to two low priority changes and two total lines of code changed. That said, 4 months is plenty of time between major releases, so I'll most likely do a release this week.

**Comment by blacksun1** [comment]
Maybe we should see what if anything happens with [Hoek issue number 196 (contain doesn't support non-enumerable properties defined with defineProperties)](https://github.com/hapijs/hoek/issues/196) as well.

**Comment by cjihrig** [comment]
Looks like that Hoek PR was merged and published in 4.1.0, so it will automatically get picked up here.

**Comment by blacksun1** [comment]
Haha. Yeah, that happened just a few minutes ago - after I wrote that comment.

**Comment by cjihrig** [comment]
v4.0.0 is published.
