### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by aredridel** [hapijs/code#92]
What changed in Code 3? What changed in Code 4?

I've got a project on code 2, and it'd be nice to know what I've got to update. I couldn't find a changelog, and certainly not a list of breaking changes.

**Comment by devinivy** [comment]
We rely on diligent milestoning and tagging to document changes.  Here's a search that should help! https://github.com/hapijs/code/issues?utf8=%E2%9C%93&q=label%3A%22breaking%20changes%22

In short, code v3 introduces `to.shallow.equal()` and makes `equal()` deep by default.  I'm actually not familiar with the changes in code v4, but my impression is that it's a subtle change that is not likely to affect many tests.

**Comment by cjihrig** [comment]
The changes all go into milestones. These are the changes for [3.0.0](https://github.com/hapijs/code/milestone/13?closed=1) and [4.0.0](https://github.com/hapijs/code/milestone/15?closed=1).

For v3, see https://github.com/hapijs/code/pull/73, which changes comparisons to be deep by default.

For v4, see https://github.com/hapijs/code/commit/88a5d243ff0086536269f6d7b8eef54fe3b35796, which only effects `include()` and the `part` flag.

**Comment by aredridel** [comment]
That'll do, I guess. Never woulda found that from any of the entry points. Still hard to tell what changed and what I need to do to update for 4. That commit message doesn't explain much.
