### ISSUE TITLE
improve deepEqual?

### ISSUE THREAD

**Issue by wabblerjs** [hapijs/code#93]
I saw you was using Hoeks deepEqual algorithm. Why? **Lodash** or this one: https://github.com/zubuzon/kewlr supports much more features. Lack of features in current implementation.

**Comment by AdriVanHoudt** [comment]
It is what the hapi ecosystem uses. You can always do `expect(strict({ 0: 'a', 1: 'b' }, ['a', 'b'])).to.be.true()` in kewlr's case

**Comment by cjihrig** [comment]
We're going to stick with the hoek implementation to minimize external dependencies, and keep consistency with the rest of the hapi ecosystem. Feel free to suggest features and improvements in the hoek repo though.
