### ISSUE TITLE
Code can actually support asynchronous assertions

### ISSUE THREAD

**Issue by antony** [hapijs/code#98]
Hi.

We've been split in our team for some while about using `code` (Which is my preference) and `chai`, which is unacceptably prone to false positives/negatives. The reason for the aversion to code was that we were doing some really ugly try/catch around the `throws` method for testing promises.

We realise that code was never designed to test promises, as the hapi team doesn't make use of them, so we resentfully started porting newer tests to `chai`.

What I've just discovered though, is that you can actually use `code` to test promises by making use of `async/await`.

```javascript
  await expect(() => {
    someService.someFunction(arg1, arg2)
  }).to.throw(Error, 'Some error message')
```

Maybe this is obvious to some people but it wasn't to anybody here, and I think a lot of people might not realise this.

Is this something that you would be interested in adding to the documentation as a side-note? Happy to write said documentation myself and open a PR, if there is interest.

**Comment by cjihrig** [comment]
Sure, I'll take a docs PR for this. Thanks!

**Comment by antony** [comment]
Cancelling this for now - our excitement was a little premature! It seems like our mocking library was throwing an error synchronously hence code being able to catch it.

I'll re-open when I've found another workaround!

**Comment by Marsup** [comment]
As opposed to asynchronously ? If you use promises you have to go all the way.

**Comment by antony** [comment]
Yeah - it looked like we were managing to wait for the exception to be thrown and catching it, but the error was being thrown immediately, at promise creation time - hence it was thrown synchronously (I think?)

**Comment by Marsup** [comment]
Everything should be wrapped if you're using promises, you can't have it both ways.
